pipeline {
    agent {
        docker {
            image 'qaninja/ruby-web-agent'
            args '--network rocklov-network'
        }
    }

    stages {
        stage('prep') {
            steps {
                sh 'cd web && bundle install'
            }
        }
        stage('Testing') {
            steps {
                sh 'cd web && rake local_seeds'
                
            }
        }
        stage('UAT'){
            steps {
                echo 'Aguardando teste de aceitação'
                input message: 'Podemos ir para produção?'
            }
        }
        stage('Prod'){
            steps {
                echo 'Webapp pronta para produção!'
            }
        }
    }
    post {
        always {
            junit 'todo'
        }
    }
}
